# Example of validated item configuration:
# number:Temperature radiator_valve_02_Set "Solltemperatur York [%.1f %unit%]" <heating1> (gRFritz_02,gRtSoll) ["Setpoint","Temperature","Property_Temperature"] { channel="avmfritz:Comet_DECT:192_168_178_1:119600949320:set_temp", widget="oh-stepper-card" [step="0.5", min=6, max=24], listWidget="oh-stepper-item" [step="0.5", min=6, max=24] }

item_types = ['color', 'contact', 'dimmer', 'group', 'image', 'location', 'number', 'player', 'rollershutter', 'string', 'switch']

feature_binary = 'binary'
features_light = 'colortemp, color'
features = feature_binary + ', ' + features_light

meta_temp = 'synonyms="Temperature"'
meta_hum = 'synonyms="Humidity"'
meta_switch = 'synonyms="switch"'
meta_light = 'synonyms="Lights, Lighting"'

tags_temp = 'sensor,Temperature'
tags_hum = 'sensor,Humidity'
tags_switch = 'switch,button'
tags_light = 'light,led'

# PLEASE DO NOT EDIT THE TABLE BELOW. ONLY USE THE FILE 'tasmota_gpios.xlsx' AND COPY THE OUTPUT TO THIS FILE!
# standard definitions (for items) for sensors and actuators:
# the gpio conversion is used to convert a sensorname like 'AM2301' to its gpio number used in tasmota to identify a sensor.
# with the gpio number is then used to get its standard values for the item
# the conversion can be found here: https://tasmota.github.io/docs/GPIO-Conversion/
std_items = {
'1':{'name':'User', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'0':{'name':'None', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1184':{'name':'DHT11', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':tags_temp+tags_hum, 'icon':''},
'1216':{'name':'AM2301', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':tags_temp+tags_hum, 'icon':''},
'1248':{'name':'SI7021', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1312':{'name':'DS18x20', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'608':{'name':'I2C SCL', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'640':{'name':'I2C SDA', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1376':{'name':'WS2812', 'std_type':item_types.index('dimmer'), 'feature':'', 'meta':'', 'tags':tags_light, 'icon':'dimmablelight'},
'1056':{'name':'IRsend', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'IR', 'icon':''},
'160':{'name':'Switch1', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'161':{'name':'Switch2', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'162':{'name':'Switch3', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'163':{'name':'Switch4', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'164':{'name':'Switch5', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'165':{'name':'Switch6', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'166':{'name':'Switch7', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'167':{'name':'Switch8', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'32':{'name':'Button1', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'33':{'name':'Button2', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'34':{'name':'Button3', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'35':{'name':'Button4', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'224':{'name':'Relay1', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'225':{'name':'Relay2', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'226':{'name':'Relay3', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'227':{'name':'Relay4', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'228':{'name':'Relay5', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'229':{'name':'Relay6', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'230':{'name':'Relay7', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'231':{'name':'Relay8', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'256':{'name':'Relay1i', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'257':{'name':'Relay2i', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'258':{'name':'Relay3i', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'259':{'name':'Relay4i', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'260':{'name':'Relay5i', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'261':{'name':'Relay6i', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'262':{'name':'Relay7i', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'263':{'name':'Relay8i', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'416':{'name':'PWM1', 'std_type':item_types.index('dimmer'), 'feature':features_light, 'meta':meta_light, 'tags':tags_light, 'icon':'dimmablelight'},
'417':{'name':'PWM2', 'std_type':item_types.index('dimmer'), 'feature':features_light, 'meta':meta_light, 'tags':tags_light, 'icon':'dimmablelight'},
'418':{'name':'PWM3', 'std_type':item_types.index('dimmer'), 'feature':features_light, 'meta':meta_light, 'tags':tags_light, 'icon':'dimmablelight'},
'419':{'name':'PWM4', 'std_type':item_types.index('dimmer'), 'feature':features_light, 'meta':meta_light, 'tags':tags_light, 'icon':'dimmablelight'},
'420':{'name':'PWM5', 'std_type':item_types.index('dimmer'), 'feature':features_light, 'meta':meta_light, 'tags':tags_light, 'icon':'dimmablelight'},
'352':{'name':'Counter1', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'353':{'name':'Counter2', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'354':{'name':'Counter3', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'355':{'name':'Counter4', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'448':{'name':'PWM1i', 'std_type':item_types.index('dimmer'), 'feature':'', 'meta':meta_light, 'tags':tags_light, 'icon':'dimmablelight'},
'449':{'name':'PWM2i', 'std_type':item_types.index('dimmer'), 'feature':'', 'meta':meta_light, 'tags':tags_light, 'icon':'dimmablelight'},
'450':{'name':'PWM3i', 'std_type':item_types.index('dimmer'), 'feature':'', 'meta':meta_light, 'tags':tags_light, 'icon':'dimmablelight'},
'451':{'name':'PWM4i', 'std_type':item_types.index('dimmer'), 'feature':'', 'meta':meta_light, 'tags':tags_light, 'icon':'dimmablelight'},
'452':{'name':'PWM5i', 'std_type':item_types.index('dimmer'), 'feature':'', 'meta':meta_light, 'tags':tags_light, 'icon':'dimmablelight'},
'1088':{'name':'IRrecv', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'288':{'name':'Led1', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'289':{'name':'Led2', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'290':{'name':'Led3', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'291':{'name':'Led4', 'std_type':item_types.index('switch'), 'feature':feature_binary, 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'320':{'name':'Led1i', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'321':{'name':'Led2i', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'322':{'name':'Led3i', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'323':{'name':'Led4i', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1408':{'name':'MHZ Rx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1440':{'name':'MHZ Tx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1472':{'name':'PZEM0XX Tx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1504':{'name':'PZEM004 Rx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1600':{'name':'SAir Rx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1632':{'name':'SAir Tx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'768':{'name':'SPI CS', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'800':{'name':'SPI DC', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'992':{'name':'BkLight', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1696':{'name':'PMS5003', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1760':{'name':'SDS0X1 Rx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1792':{'name':'SerBr Rx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1824':{'name':'SerBr Tx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1856':{'name':'SR04 Tri', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1888':{'name':'SR04 Ech', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1920':{'name':'SDMx20 Tx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1952':{'name':'SDMx20 Rx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1984':{'name':'SDM630 Tx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2016':{'name':'SDM630 Rx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2048':{'name':'TM16 CLK', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2080':{'name':'TM16 DIO', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2112':{'name':'TM16 STB', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'192':{'name':'Switch1n', 'std_type':item_types.index('switch'), 'feature':'', 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'193':{'name':'Switch2n', 'std_type':item_types.index('switch'), 'feature':'', 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'194':{'name':'Switch3n', 'std_type':item_types.index('switch'), 'feature':'', 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'195':{'name':'Switch4n', 'std_type':item_types.index('switch'), 'feature':'', 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'196':{'name':'Switch5n', 'std_type':item_types.index('switch'), 'feature':'', 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'197':{'name':'Switch6n', 'std_type':item_types.index('switch'), 'feature':'', 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'198':{'name':'Switch7n', 'std_type':item_types.index('switch'), 'feature':'', 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'199':{'name':'Switch8n', 'std_type':item_types.index('switch'), 'feature':'', 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'64':{'name':'Button1n', 'std_type':item_types.index('switch'), 'feature':'', 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'65':{'name':'Button2n', 'std_type':item_types.index('switch'), 'feature':'', 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'66':{'name':'Button3n', 'std_type':item_types.index('switch'), 'feature':'', 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'67':{'name':'Button4n', 'std_type':item_types.index('switch'), 'feature':'', 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'384':{'name':'Counter1n', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'385':{'name':'Counter2n', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'386':{'name':'Counter3n', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'387':{'name':'Counter4n', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1536':{'name':'PZEM016 Rx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1568':{'name':'PZEM017 Rx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2144':{'name':'MP3 Player', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1728':{'name':'SDS0X1 Tx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2176':{'name':'HX711 SCK', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2208':{'name':'HX711 DAT', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2240':{'name':'TX20', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1120':{'name':'RFSend', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1152':{'name':'RFrecv', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2272':{'name':'Tuya Tx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2304':{'name':'Tuya Rx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2336':{'name':'MGC3130 Xfr', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2368':{'name':'MGC3130 Rst', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'832':{'name':'SSPI MISO', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'864':{'name':'SSPI MOSI', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'896':{'name':'SSPI SCLK', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'928':{'name':'SSPI CS', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'960':{'name':'SSPI DC', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2400':{'name':'RF Sensor', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2432':{'name':'AZ Rx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2464':{'name':'AZ Tx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2496':{'name':'MX31855 CS', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2528':{'name':'MX31855 CLK', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2560':{'name':'MX31855 DO', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'96':{'name':'Button1i', 'std_type':item_types.index('switch'), 'feature':'', 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'97':{'name':'Button2i', 'std_type':item_types.index('switch'), 'feature':'', 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'98':{'name':'Button3i', 'std_type':item_types.index('switch'), 'feature':'', 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'99':{'name':'Button4i', 'std_type':item_types.index('switch'), 'feature':'', 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'128':{'name':'Button1in', 'std_type':item_types.index('switch'), 'feature':'', 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'129':{'name':'Button2in', 'std_type':item_types.index('switch'), 'feature':'', 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'130':{'name':'Button3in', 'std_type':item_types.index('switch'), 'feature':'', 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'131':{'name':'Button4in', 'std_type':item_types.index('switch'), 'feature':'', 'meta':meta_switch, 'tags':tags_switch, 'icon':'switch'},
'2592':{'name':'HLWBL SEL', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2624':{'name':'HLWBL SELi', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2656':{'name':'HLWBL CF1', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2688':{'name':'HLW8012 CF', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2720':{'name':'BL0937 CF', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2752':{'name':'MCP39F5 Tx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2784':{'name':'MCP39F5 Rx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2816':{'name':'MCP39F5 Rst', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2848':{'name':'PN532 Tx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2880':{'name':'PN532 Rx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2912':{'name':'SM16716 CLK', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2944':{'name':'SM16716 DAT', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'2976':{'name':'SM16716 PWR', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3008':{'name':'MY92x1 DI', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3040':{'name':'MY92x1 DCKI', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3072':{'name':'CSE7766 Tx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3104':{'name':'CSE7766 Rx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3136':{'name':'ALux IrRcv', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3200':{'name':'Serial Tx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3232':{'name':'Serial Rx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3264':{'name':'Rotary1a', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3296':{'name':'Rotary1b', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3265':{'name':'Rotary2a', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3297':{'name':'Rotary2b', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3392':{'name':'HRE CLOCK', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3424':{'name':'HRE DATA', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3456':{'name':'ADE7953_IRQ', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'544':{'name':'LedLink', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'576':{'name':'LedLinki', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3168':{'name':'ALux IrSel', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'480':{'name':'Buzzer', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'512':{'name':'Buzzeri', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1024':{'name':'OLED Reset', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3488':{'name':'SolaxX1 Tx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3520':{'name':'SolaxX1 Rx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3552':{'name':'Zigbee Tx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3584':{'name':'Zigbee Rx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3616':{'name':'RDM6300 Rx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3648':{'name':'iBeacon Tx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3680':{'name':'iBeacon Rx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3712':{'name':'A4988 DIR', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3744':{'name':'A4988 STP', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3776':{'name':'A4988 ENA', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3808':{'name':'A4988 MS1', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3809':{'name':'A4988 MS2', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3810':{'name':'A4988 MS3', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3904':{'name':'DDS238-2 Tx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3936':{'name':'DDS238-2 Rx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'3968':{'name':'DDSU666 Tx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4000':{'name':'DDSU666 Rx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4032':{'name':'SM2135 CLK', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4064':{'name':'SM2135 DAT', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4096':{'name':'DeepSleep', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4128':{'name':'EXS Enable', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4160':{'name':'Slave TX', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4192':{'name':'Slave RX', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4224':{'name':'Slave RST', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4256':{'name':'Slave RSTi', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4288':{'name':'HPMA RX', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4320':{'name':'HPMA TX', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4352':{'name':'GPS RX', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4384':{'name':'GPS TX', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1344':{'name':'DSB OUT', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1280':{'name':'DHT11 OUT', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4416':{'name':'HM10 RX', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4448':{'name':'HM10 TX', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4480':{'name':'LE01MR RX', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4512':{'name':'LE01MR TX', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4544':{'name':'CC1101 GDO0', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4576':{'name':'CC1101 GDO2', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4608':{'name':'HRXL RX', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4640':{'name':'MOODL TX', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4672':{'name':'AS3935', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'1664':{'name':'PMS5003 TX', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4928':{'name':'Boiler OT Rx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4960':{'name':'Boiler OT Tx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'4992':{'name':'Windmeter Speed', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'5056':{'name':'BL0940 RX', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'5088':{'name':'TCP TX', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'5120':{'name':'TCP RX', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'5152':{'name':'TELEINFO RX', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'5184':{'name':'TELEINFO Enable', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'5216':{'name':'LMT01', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'5248':{'name':'IEM3000 TX', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'5280':{'name':'IEM3000 RX', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'5312':{'name':'Zigbee RST', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},
'5344':{'name':'DYP Rx', 'std_type':item_types.index('number'), 'feature':'', 'meta':'', 'tags':'', 'icon':''},


'default': {'name': 'Default', 'std_type': item_types.index('number'), 'feature': '', 'meta': '', 'tags': '', 'icon': ''}  # default value, dont delete!
}
